### PR TITLE
Add support for python 3 11

### PR DESCRIPTION
**Pull request by zosiek666**
Fixing https://github.com/jkehler/awslambda-psycopg2/issues/83

### CODE REVIEW

**Comment by rizbihassan** [comment]
Can the admin approve this PR?

**Comment by avaki11** [comment]
@zosiek666 does this include any ssl support ?

**Comment by leandrokemp** [comment]
@jkehler Could you please approve this PR?

**Review by max-lobur — APPROVED** [review]

**Comment by jaramd** [comment]
@zosiek666 the pr is approved, could you please merge if you have acess?

**Comment by glauber-experian** [comment]
Please merge! Thanks.

**Comment by glauber-experian** [comment]
@jkehler - please merge, thanks!

**Comment by zosiek666** [comment]
I do not have write access, so somebody with write access mus merge it

**Comment by jkehler** [comment]
Sorry guys for not being that active here. I've just merged this in. Thanks for the contributions!

**Pull request merged**
